### ISSUE TITLE
Add two variations of the same product

### ISSUE THREAD

**Issue by renatogp** [chrisglass/django-shop-simplevariations#1]
Is this possible to add two variations of the same product using this approach?

**Comment by chrisglass** [comment]
Yes, simply bind two option groups to your product.
I'll add more docs as soon as possible, sorry about that :(

**Comment by renatogp** [comment]
It's ok! We can follow the code to understand :)
My doubt i that there will be only one "cart_item" instance, right? Should I treat this in the template side using the "extra_price_fields" list?

Thanks!

**Comment by chrisglass** [comment]
Ahhh yeah, I get it now :)

Yes, normally adding several variations to the same product should make only one cartitem (a computer with options "red" and "ssd drive" for example). Otherwise it's a bug I should fix :)

**Comment by bmihelac** [comment]
in project I am working on I made two models, BaseProduct is model.Model subclass and ProductVariation as subclass of Product.
This way cart always contains variations, example:

```
  class ProductVariation(Product):
      baseproduct = models.ForeignKey(BaseProduct, related_name='variations')
      options = models.ManyToManyField(Option, related_name='variations',
          blank=True, null=True, verbose_name=_('options'))
```

hope it helps
